name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - develop

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Đảm bảo lấy toàn bộ repo

      - name: Debug - Kiểm tra file và thư mục
        run: ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate pom.xml if not exists
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "<project>" > pom.xml
            echo "  <modelVersion>4.0.0</modelVersion>" >> pom.xml
            echo "  <groupId>com.example</groupId>" >> pom.xml
            echo "  <artifactId>example-project</artifactId>" >> pom.xml
            echo "  <version>1.0-SNAPSHOT</version>" >> pom.xml
            echo "</project>" >> pom.xml
          fi

      - name: Run SonarQube Scan
        run: |
          if [ -f "pom.xml" ]; then
            mvn sonar:sonar \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
              -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          else
            echo "pom.xml không tồn tại trong thư mục chính. Kiểm tra lại!"
            exit 1
          fi

